apiVersion: v1
kind: Service
metadata:
  name: student-api
  namespace: student-api
  labels:
    app: student-api
spec:
  type: {{ .Values.service.type }}

  selector:
    app: student-api

  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}