apiVersion: v1
kind: Namespace
metadata:
  name: student-api
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: student-api-config
  namespace: student-api
data:
  PORT: "8080"
  DB_HOST: "student-api-db"
  DB_PORT: "5432"
  DB_NAME: "student_api"
  DB_SSLMODE: "disable"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-api
  namespace: student-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-api
  template:
    metadata:
      labels:
        app: student-api

    spec:
      nodeSelector:
        type: application
      initContainers:
      - name: db-migration
        image: cvmaldar234/student-api-migrate:1.0.0

        command:
        - migrate
        - -path
        - /migrations
        - -database
        - postgres://$(DB_USERNAME):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?sslmode=$(DB_SSLMODE)
        - up

        envFrom:
        - configMapRef:
            name: student-api-config
        - secretRef:
            name: student-api-db-secret
      containers:
      - name: student-api
        image: cvmaldar234/student-api:1.0.1

        ports:
        - containerPort: 8080

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

        envFrom:
        - configMapRef:
            name: student-api-config
        - secretRef:
            name: student-api-db-secret
---
apiVersion: v1
kind: Service
metadata:
  name: student-api
  namespace: student-api
spec:
  type: ClusterIP

  selector:
    app: student-api

  ports:
  - port: 8080
    targetPort: 8080
