apiVersion: v1
kind: Secret
metadata:
  name: github-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository

type: Opaque

stringData:
  url: https://github.com/Cvmaldar/one2n-SRE-bootcampv2.git
  username: Cvmaldar
  password: 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
