apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-api-db
  namespace: student-api

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: student-api-db

  template:
    metadata:
      labels:
        app: student-api-db

    spec:
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}

      containers:
        - name: postgres
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: 5432

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: student-api-db-config
                  key: POSTGRES_DB

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: student-api-db-secret
                  key: DB_USERNAME

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: student-api-db-secret
                  key: DB_PASSWORD