apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blackbox-exporter
  namespace: argocd

spec:
  project: default

  sources:
  # Upstream Helm chart
  - repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus-blackbox-exporter
    targetRevision: "11.17.2"

    helm:
      releaseName: blackbox-exporter

      valueFiles:
      - $values/helm/observability/blackbox/values.yaml

  # Git repository containing values.yaml
  - repoURL: https://github.com/Cvmaldar/one2n-SRE-bootcampv2.git
    targetRevision: main
    ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
    - CreateNamespace=true
