apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-exporter-secret
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/Cvmaldar/one2n-SRE-bootcampv2.git
    targetRevision: main
    path: helm/observability/postgres-exporter-secret

  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  syncOptions:
  - CreateNamespace=true
