replicaCount: 1

image:
  repository: postgres
  tag: "17"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432
  targetPort: 5432

nodeSelector:
  type: database

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

config:
  POSTGRES_DB: "student_api"