apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend

spec:
  provider:
    vault:
      server: {{ .Values.vault.server | quote }}
      path: {{ .Values.vault.path | quote }}
      version: {{ .Values.vault.version | quote }}

      auth:
        tokenSecretRef:
          name: {{ .Values.vault.auth.secretName }}
          namespace: {{ .Values.vault.auth.secretNamespace }}
          key: {{ .Values.vault.auth.secretKey }}